server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # 1. Ruta para Exámenes
        - id: ruta-examenes
          uri: lb://EXAMENES
          predicates:
            - Path=/examenes/**

        # 2. Ruta para Citas
        - id: ruta-citas
          uri: lb://CITAS
          predicates:
            - Path=/citas/**

        # 3. Ruta para Recetas
        - id: ruta-recetas
          uri: lb://RECETAS
          predicates:
            - Path=/recetas/**
        
        # 4. Ruta para Autenticación
        - id: ruta-autenticacion
          uri: lb://AUTENTICACION
          predicates:
            - Path=/autenticacion/**

        # 5. Ruta para Pagos
        - id: ruta-pagos
          uri: lb://PAGOS
          predicates:
            - Path=/pagos/**
        
        # 6. Ruta para Notificaciones
        - id: ruta-notificaciones
          uri: lb://NOTIFICACIONES
          predicates:
            - Path=/notificaciones/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: 127.0.0.1:${spring.application.name}:${server.port}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG